# Generated by Django 4.1.6 on 2023-02-11 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_cart', '0001_initial'),
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GameModel',
            new_name='GamesModel',
        ),
    ]
